=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'

# Unit tests for Aryeo::VendorsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VendorsApi' do
  before do
    # run before each test
    @api_instance = Aryeo::VendorsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VendorsApi' do
    it 'should create an instance of VendorsApi' do
      expect(@api_instance).to be_instance_of(Aryeo::VendorsApi)
    end
  end

  # unit tests for get_vendors
  # Get vendors available to a group.
  # Get vendors available to a group.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma separated list of optional data to include in the response.
  # @return [GroupCollection]
  describe 'get_vendors test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_vendors_id
  # Get vendors available to a group.
  # Get information about a vendor.
  # @param vendor_id The ID of the group that is associated as a vendor. UUID Version 4.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma separated list of optional data to include in the response.
  # @return [GroupResource]
  describe 'get_vendors_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
