=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'

# Unit tests for Aryeo::VendorsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VendorsApi' do
  before do
    # run before each test
    @api_instance = Aryeo::VendorsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VendorsApi' do
    it 'should create an instance of VendorsApi' do
      expect(@api_instance).to be_instance_of(Aryeo::VendorsApi)
    end
  end

  # unit tests for get_vendors
  # Get vendors available to a group.
  # Get vendors available to a group.
  # @param [Hash] opts the optional parameters
  # @return [GroupCollection]
  describe 'get_vendors test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_vendors_search
  # Get vendors that can be added to the group&#39;s vendor list.
  # Get vendors that can be added to the group&#39;s vendor list, excluding those already available to a group. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :query A search query.
  # @option opts [String] :per_page The number of items per page. Defaults to 25.
  # @option opts [String] :page The requested page. Defaults to 1.
  # @return [GroupCollection]
  describe 'get_vendors_search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
