=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Aryeo::ApiFail422
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Aryeo::ApiFail422 do
  let(:instance) { Aryeo::ApiFail422.new }

  describe 'test an instance of ApiFail422' do
    it 'should create an instance of ApiFail422' do
      expect(instance).to be_instance_of(Aryeo::ApiFail422)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
