=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Aryeo::AppointmentCancelPutPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Aryeo::AppointmentCancelPutPayload do
  let(:instance) { Aryeo::AppointmentCancelPutPayload.new }

  describe 'test an instance of AppointmentCancelPutPayload' do
    it 'should create an instance of AppointmentCancelPutPayload' do
      expect(instance).to be_instance_of(Aryeo::AppointmentCancelPutPayload)
    end
  end
  describe 'test attribute "notify_customer"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
