=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Aryeo::ListingPrice
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Aryeo::ListingPrice do
  let(:instance) { Aryeo::ListingPrice.new }

  describe 'test an instance of ListingPrice' do
    it 'should create an instance of ListingPrice' do
      expect(instance).to be_instance_of(Aryeo::ListingPrice)
    end
  end
  describe 'test attribute "list_price"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
