=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Aryeo::ListingLot
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Aryeo::ListingLot do
  let(:instance) { Aryeo::ListingLot.new }

  describe 'test an instance of ListingLot' do
    it 'should create an instance of ListingLot' do
      expect(instance).to be_instance_of(Aryeo::ListingLot)
    end
  end
  describe 'test attribute "size_acres"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "open_parking_spaces"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
