=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Aryeo::MarketingMaterialPublishPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Aryeo::MarketingMaterialPublishPayload do
  let(:instance) { Aryeo::MarketingMaterialPublishPayload.new }

  describe 'test an instance of MarketingMaterialPublishPayload' do
    it 'should create an instance of MarketingMaterialPublishPayload' do
      expect(instance).to be_instance_of(Aryeo::MarketingMaterialPublishPayload)
    end
  end
  describe 'test attribute "polotno_json"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
