=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Aryeo::MarketingMaterialTemplatePublishPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Aryeo::MarketingMaterialTemplatePublishPayload do
  let(:instance) { Aryeo::MarketingMaterialTemplatePublishPayload.new }

  describe 'test an instance of MarketingMaterialTemplatePublishPayload' do
    it 'should create an instance of MarketingMaterialTemplatePublishPayload' do
      expect(instance).to be_instance_of(Aryeo::MarketingMaterialTemplatePublishPayload)
    end
  end
  describe 'test attribute "polotno_json"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
