=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Aryeo::ProductItem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Aryeo::ProductItem do
  let(:instance) { Aryeo::ProductItem.new }

  describe 'test an instance of ProductItem' do
    it 'should create an instance of ProductItem' do
      expect(instance).to be_instance_of(Aryeo::ProductItem)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
