=begin
#Aryeo


Contact: jarrod@aryeo.com
=end

require 'date'
require 'time'

module Aryeo
  # A payment request for some content or service.
  class Order
    # ID of the order. UUID Version 4.
    attr_accessor :id

    # A vanity id used for internal tracking of orders for a given vendor.
    attr_accessor :number

    # The title of the order, generated by combining the order's number property with the prefix \"Order #\".
    attr_accessor :title

    # The fulfillment status of the order.
    attr_accessor :fulfillment_status

    # The payment status of the order.
    attr_accessor :payment_status

    # The three-letter ISO 4217 currency code for the currency in which this order was or will be transacted. Must be a supported currency of Aryeo.
    attr_accessor :currency

    # A positive integer in the smallest currency unit (that is, 100 cents for $1.00) representing the total order amount that was or will be charged. This accounts for order items and taxes. 
    attr_accessor :total_amount

    # A URL of a publicly-accessible webpage to pay for the order.
    attr_accessor :payment_url

    # A URL of a publicly-accessible webpage to see the order's status.
    attr_accessor :status_url

    attr_accessor :address

    attr_accessor :customer

    attr_accessor :listing

    # items
    attr_accessor :items

    attr_accessor :appointments

    attr_accessor :unconfirmed_appointments

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'number' => :'number',
        :'title' => :'title',
        :'fulfillment_status' => :'fulfillment_status',
        :'payment_status' => :'payment_status',
        :'currency' => :'currency',
        :'total_amount' => :'total_amount',
        :'payment_url' => :'payment_url',
        :'status_url' => :'status_url',
        :'address' => :'address',
        :'customer' => :'customer',
        :'listing' => :'listing',
        :'items' => :'items',
        :'appointments' => :'appointments',
        :'unconfirmed_appointments' => :'unconfirmed_appointments'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'number' => :'Integer',
        :'title' => :'String',
        :'fulfillment_status' => :'String',
        :'payment_status' => :'String',
        :'currency' => :'String',
        :'total_amount' => :'Integer',
        :'payment_url' => :'String',
        :'status_url' => :'String',
        :'address' => :'Address',
        :'customer' => :'Group',
        :'listing' => :'Listing',
        :'items' => :'Array<OrderItem>',
        :'appointments' => :'Array<Appointment>',
        :'unconfirmed_appointments' => :'Array<UnconfirmedAppointment>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'payment_url',
        :'status_url',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Aryeo::Order` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Aryeo::Order`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'fulfillment_status')
        self.fulfillment_status = attributes[:'fulfillment_status']
      end

      if attributes.key?(:'payment_status')
        self.payment_status = attributes[:'payment_status']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      end

      if attributes.key?(:'payment_url')
        self.payment_url = attributes[:'payment_url']
      end

      if attributes.key?(:'status_url')
        self.status_url = attributes[:'status_url']
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'customer')
        self.customer = attributes[:'customer']
      end

      if attributes.key?(:'listing')
        self.listing = attributes[:'listing']
      end

      if attributes.key?(:'items')
        if (value = attributes[:'items']).is_a?(Array)
          self.items = value
        end
      end

      if attributes.key?(:'appointments')
        if (value = attributes[:'appointments']).is_a?(Array)
          self.appointments = value
        end
      end

      if attributes.key?(:'unconfirmed_appointments')
        if (value = attributes[:'unconfirmed_appointments']).is_a?(Array)
          self.unconfirmed_appointments = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @id.to_s.length > 36
        invalid_properties.push('invalid value for "id", the character length must be smaller than or equal to 36.')
      end

      if @id.to_s.length < 36
        invalid_properties.push('invalid value for "id", the character length must be great than or equal to 36.')
      end

      if @number.nil?
        invalid_properties.push('invalid value for "number", number cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @title.to_s.length > 255
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 255.')
      end

      if @title.to_s.length < 0
        invalid_properties.push('invalid value for "title", the character length must be great than or equal to 0.')
      end

      if @fulfillment_status.nil?
        invalid_properties.push('invalid value for "fulfillment_status", fulfillment_status cannot be nil.')
      end

      if @fulfillment_status.to_s.length > 255
        invalid_properties.push('invalid value for "fulfillment_status", the character length must be smaller than or equal to 255.')
      end

      if @fulfillment_status.to_s.length < 0
        invalid_properties.push('invalid value for "fulfillment_status", the character length must be great than or equal to 0.')
      end

      if @payment_status.nil?
        invalid_properties.push('invalid value for "payment_status", payment_status cannot be nil.')
      end

      if @payment_status.to_s.length > 255
        invalid_properties.push('invalid value for "payment_status", the character length must be smaller than or equal to 255.')
      end

      if @payment_status.to_s.length < 0
        invalid_properties.push('invalid value for "payment_status", the character length must be great than or equal to 0.')
      end

      if !@currency.nil? && @currency.to_s.length > 255
        invalid_properties.push('invalid value for "currency", the character length must be smaller than or equal to 255.')
      end

      if !@currency.nil? && @currency.to_s.length < 0
        invalid_properties.push('invalid value for "currency", the character length must be great than or equal to 0.')
      end

      if !@total_amount.nil? && @total_amount < 0
        invalid_properties.push('invalid value for "total_amount", must be greater than or equal to 0.')
      end

      if !@payment_url.nil? && @payment_url.to_s.length > 65535
        invalid_properties.push('invalid value for "payment_url", the character length must be smaller than or equal to 65535.')
      end

      if !@payment_url.nil? && @payment_url.to_s.length < 0
        invalid_properties.push('invalid value for "payment_url", the character length must be great than or equal to 0.')
      end

      if @status_url.to_s.length > 65535
        invalid_properties.push('invalid value for "status_url", the character length must be smaller than or equal to 65535.')
      end

      if @status_url.to_s.length < 0
        invalid_properties.push('invalid value for "status_url", the character length must be great than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @id.to_s.length > 36
      return false if @id.to_s.length < 36
      return false if @number.nil?
      return false if @title.nil?
      return false if @title.to_s.length > 255
      return false if @title.to_s.length < 0
      return false if @fulfillment_status.nil?
      fulfillment_status_validator = EnumAttributeValidator.new('String', ["FULFILLED", "UNFULFILLED"])
      return false unless fulfillment_status_validator.valid?(@fulfillment_status)
      return false if @fulfillment_status.to_s.length > 255
      return false if @fulfillment_status.to_s.length < 0
      return false if @payment_status.nil?
      payment_status_validator = EnumAttributeValidator.new('String', ["PAID", "UNPAID"])
      return false unless payment_status_validator.valid?(@payment_status)
      return false if @payment_status.to_s.length > 255
      return false if @payment_status.to_s.length < 0
      currency_validator = EnumAttributeValidator.new('String', ["USD", "CAD", "GBP", "CHF", "EUR", "AUD", "NZD", "ZAR"])
      return false unless currency_validator.valid?(@currency)
      return false if !@currency.nil? && @currency.to_s.length > 255
      return false if !@currency.nil? && @currency.to_s.length < 0
      return false if !@total_amount.nil? && @total_amount < 0
      return false if !@payment_url.nil? && @payment_url.to_s.length > 65535
      return false if !@payment_url.nil? && @payment_url.to_s.length < 0
      return false if @status_url.to_s.length > 65535
      return false if @status_url.to_s.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      if id.to_s.length > 36
        fail ArgumentError, 'invalid value for "id", the character length must be smaller than or equal to 36.'
      end

      if id.to_s.length < 36
        fail ArgumentError, 'invalid value for "id", the character length must be great than or equal to 36.'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      if title.to_s.length > 255
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 255.'
      end

      if title.to_s.length < 0
        fail ArgumentError, 'invalid value for "title", the character length must be great than or equal to 0.'
      end

      @title = title
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] fulfillment_status Object to be assigned
    def fulfillment_status=(fulfillment_status)
      validator = EnumAttributeValidator.new('String', ["FULFILLED", "UNFULFILLED"])
      unless validator.valid?(fulfillment_status)
        fail ArgumentError, "invalid value for \"fulfillment_status\", must be one of #{validator.allowable_values}."
      end
      @fulfillment_status = fulfillment_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] payment_status Object to be assigned
    def payment_status=(payment_status)
      validator = EnumAttributeValidator.new('String', ["PAID", "UNPAID"])
      unless validator.valid?(payment_status)
        fail ArgumentError, "invalid value for \"payment_status\", must be one of #{validator.allowable_values}."
      end
      @payment_status = payment_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] currency Object to be assigned
    def currency=(currency)
      validator = EnumAttributeValidator.new('String', ["USD", "CAD", "GBP", "CHF", "EUR", "AUD", "NZD", "ZAR"])
      unless validator.valid?(currency)
        fail ArgumentError, "invalid value for \"currency\", must be one of #{validator.allowable_values}."
      end
      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] total_amount Value to be assigned
    def total_amount=(total_amount)
      if !total_amount.nil? && total_amount < 0
        fail ArgumentError, 'invalid value for "total_amount", must be greater than or equal to 0.'
      end

      @total_amount = total_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_url Value to be assigned
    def payment_url=(payment_url)
      if !payment_url.nil? && payment_url.to_s.length > 65535
        fail ArgumentError, 'invalid value for "payment_url", the character length must be smaller than or equal to 65535.'
      end

      if !payment_url.nil? && payment_url.to_s.length < 0
        fail ArgumentError, 'invalid value for "payment_url", the character length must be great than or equal to 0.'
      end

      @payment_url = payment_url
    end

    # Custom attribute writer method with validation
    # @param [Object] status_url Value to be assigned
    def status_url=(status_url)
      if status_url.to_s.length > 65535
        fail ArgumentError, 'invalid value for "status_url", the character length must be smaller than or equal to 65535.'
      end

      if status_url.to_s.length < 0
        fail ArgumentError, 'invalid value for "status_url", the character length must be great than or equal to 0.'
      end

      @status_url = status_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          number == o.number &&
          title == o.title &&
          fulfillment_status == o.fulfillment_status &&
          payment_status == o.payment_status &&
          currency == o.currency &&
          total_amount == o.total_amount &&
          payment_url == o.payment_url &&
          status_url == o.status_url &&
          address == o.address &&
          customer == o.customer &&
          listing == o.listing &&
          items == o.items &&
          appointments == o.appointments &&
          unconfirmed_appointments == o.unconfirmed_appointments
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, number, title, fulfillment_status, payment_status, currency, total_amount, payment_url, status_url, address, customer, listing, items, appointments, unconfirmed_appointments].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Aryeo.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
